In [1]:
from sklearn import tree
import pandas as pd
import os
import pickle

In [2]:
df = pd.read_csv(os.path.join("..", "Resources", "movies_final.csv"))
df.head()

,genres_name_Action,genres_name_Adventure,genres_name_Animation,genres_name_Comedy,genres_name_Crime,genres_name_Documentary,genres_name_Drama,genres_name_Family,genres_name_Fantasy,genres_name_Foreign,...,actor_name_William Hurt,actor_name_William Shatner,actor_name_Winona Ryder,actor_name_Woody Allen,actor_name_Woody Harrelson,actor_name_Xander Berkeley,budgetbin_0,budgetbin_1,budgetbin_2,Profitable
0,0,0,0,1,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,1,1
1,1,1,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,1
2,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,1,1
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,1
4,0,0,0,0,1,0,1,0,0,0,...,0,0,0,0,0,0,0,0,1,1

In [3]:
data = df.drop("Profitable", axis=1)
feature_names = data.columns
data.head()

,genres_name_Action,genres_name_Adventure,genres_name_Animation,genres_name_Comedy,genres_name_Crime,genres_name_Documentary,genres_name_Drama,genres_name_Family,genres_name_Fantasy,genres_name_Foreign,...,actor_name_William Holden,actor_name_William Hurt,actor_name_William Shatner,actor_name_Winona Ryder,actor_name_Woody Allen,actor_name_Woody Harrelson,actor_name_Xander Berkeley,budgetbin_0,budgetbin_1,budgetbin_2
0,0,0,0,1,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,1
1,1,1,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,1
2,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,1
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
4,0,0,0,0,1,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [4]:
target = df['Profitable']
# target_names = ["loss", "low", "medium", "high"]

In [5]:
# from sklearn.model_selection import train_test_split
# X_train, X_test, y_train, y_test = train_test_split(data, target, random_state=42)

In [6]:
# clf = tree.DecisionTreeClassifier()
# clf = clf.fit(X_train, y_train)
# clf.score(X_test, y_test)

In [7]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from keras.utils import to_categorical

X_train, X_test, y_train, y_test = train_test_split(
    data, target, random_state=1, stratify=target)
X_scaler = StandardScaler().fit(X_train)
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)


# Step 1: Label-encode data set
label_encoder = LabelEncoder()
label_encoder.fit(y_train)
encoded_y_train = label_encoder.transform(y_train)
encoded_y_test = label_encoder.transform(y_test)

# Step 2: Convert encoded labels to one-hot-encoding
y_train_categorical = to_categorical(encoded_y_train)
y_test_categorical = to_categorical(encoded_y_test)

Using TensorFlow backend.
C:\Users\naras\Miniconda3\envs\ml-env\lib\site-packages\sklearn\preprocessing\data.py:645: DataConversionWarning: Data with input dtype int64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
C:\Users\naras\Miniconda3\envs\ml-env\lib\site-packages\ipykernel_launcher.py:8: DataConversionWarning: Data with input dtype int64 were all converted to float64 by StandardScaler.

C:\Users\naras\Miniconda3\envs\ml-env\lib\site-packages\ipykernel_launcher.py:9: DataConversionWarning: Data with input dtype int64 were all converted to float64 by StandardScaler.
  if __name__ == '__main__':

In [8]:
#feature_imp = sorted(zip(model.feature_importances_, feature_names), reverse=True)

In [9]:
#feature_imp

In [10]:
# [feature[0] > .01 for feature in feature_imp]

In [11]:
# from sklearn.externals import joblib
# # Output a pickle file for the model
# joblib.dump(rf, '../Resources/cinematic_crystal_ball.pkl')

In [40]:
#Create a deep learning model
from keras.models import Sequential
from keras.layers import Dense


# Create model and add layers
model = Sequential()
model.add(Dense(units=500, activation='relu', input_dim=1141))
model.add(Dense(units=500, activation='relu'))
model.add(Dense(units=200, activation='relu'))
# model.add(Dense(units=100, activation='relu'))
# model.add(Dense(units=100, activation='relu'))
model.add(Dense(units=2, activation='softmax'))

In [41]:
# Compile and fit the model
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])
model.fit(
    X_train,
    y_train_categorical,
    epochs=100,
    shuffle=True,
    verbose=2
)
# model.fit(
#     X_train_scaled,
#     y_train_categorical,
#     epochs=25,
#     shuffle=True,
#     verbose=2
# )

Epoch 1/100
 - 1s - loss: 0.5565 - acc: 0.7690
Epoch 2/100
 - 0s - loss: 0.4088 - acc: 0.7921
Epoch 3/100
 - 0s - loss: 0.2773 - acc: 0.8284
Epoch 4/100
 - 0s - loss: 0.1389 - acc: 0.9802
Epoch 5/100
 - 0s - loss: 0.0353 - acc: 0.9967
Epoch 6/100
 - 0s - loss: 0.0027 - acc: 1.0000
Epoch 7/100
 - 0s - loss: 5.2833e-04 - acc: 1.0000
Epoch 8/100
 - 0s - loss: 1.8173e-04 - acc: 1.0000
Epoch 9/100
 - 0s - loss: 1.1050e-04 - acc: 1.0000
Epoch 10/100
 - 0s - loss: 8.4227e-05 - acc: 1.0000
Epoch 11/100
 - 0s - loss: 7.1739e-05 - acc: 1.0000
Epoch 12/100
 - 0s - loss: 6.4037e-05 - acc: 1.0000
Epoch 13/100
 - 0s - loss: 5.8077e-05 - acc: 1.0000
Epoch 14/100
 - 0s - loss: 5.2833e-05 - acc: 1.0000
Epoch 15/100
 - 0s - loss: 4.8895e-05 - acc: 1.0000
Epoch 16/100
 - 0s - loss: 4.5320e-05 - acc: 1.0000
Epoch 17/100
 - 0s - loss: 4.2201e-05 - acc: 1.0000
Epoch 18/100
 - 0s - loss: 3.9375e-05 - acc: 1.0000
Epoch 19/100
 - 0s - loss: 3.6628e-05 - acc: 1.0000
Epoch 20/100
 - 0s - loss: 3.4411e-05 - acc: 1.0000
Epoch 21/100
 - 0s - loss: 3.2227e-05 - acc: 1.0000
Epoch 22/100
 - 0s - loss: 3.0312e-05 - acc: 1.0000
Epoch 23/100
 - 0s - loss: 2.8347e-05 - acc: 1.0000
Epoch 24/100
 - 0s - loss: 2.6691e-05 - acc: 1.0000
Epoch 25/100
 - 0s - loss: 2.5230e-05 - acc: 1.0000
Epoch 26/100
 - 0s - loss: 2.3884e-05 - acc: 1.0000
Epoch 27/100
 - 0s - loss: 2.2497e-05 - acc: 1.0000
Epoch 28/100
 - 0s - loss: 2.1327e-05 - acc: 1.0000
Epoch 29/100
 - 0s - loss: 2.0045e-05 - acc: 1.0000
Epoch 30/100
 - 0s - loss: 1.9082e-05 - acc: 1.0000
Epoch 31/100
 - 0s - loss: 1.8076e-05 - acc: 1.0000
Epoch 32/100
 - 0s - loss: 1.7107e-05 - acc: 1.0000
Epoch 33/100
 - 0s - loss: 1.6325e-05 - acc: 1.0000
Epoch 34/100
 - 0s - loss: 1.5488e-05 - acc: 1.0000
Epoch 35/100
 - 0s - loss: 1.4739e-05 - acc: 1.0000
Epoch 36/100
 - 0s - loss: 1.4091e-05 - acc: 1.0000
Epoch 37/100
 - 0s - loss: 1.3409e-05 - acc: 1.0000
Epoch 38/100
 - 0s - loss: 1.2822e-05 - acc: 1.0000
Epoch 39/100
 - 0s - loss: 1.2203e-05 - acc: 1.0000
Epoch 40/100
 - 0s - loss: 1.1671e-05 - acc: 1.0000
Epoch 41/100
 - 0s - loss: 1.1172e-05 - acc: 1.0000
Epoch 42/100
 - 0s - loss: 1.0679e-05 - acc: 1.0000
Epoch 43/100
 - 0s - loss: 1.0239e-05 - acc: 1.0000
Epoch 44/100
 - 0s - loss: 9.8053e-06 - acc: 1.0000
Epoch 45/100
 - 0s - loss: 9.4293e-06 - acc: 1.0000
Epoch 46/100
 - 0s - loss: 9.0524e-06 - acc: 1.0000
Epoch 47/100
 - 0s - loss: 8.7048e-06 - acc: 1.0000
Epoch 48/100
 - 0s - loss: 8.3587e-06 - acc: 1.0000
Epoch 49/100
 - 0s - loss: 8.0471e-06 - acc: 1.0000
Epoch 50/100
 - 0s - loss: 7.7359e-06 - acc: 1.0000
Epoch 51/100
 - 0s - loss: 7.4536e-06 - acc: 1.0000
Epoch 52/100
 - 0s - loss: 7.1539e-06 - acc: 1.0000
Epoch 53/100
 - 0s - loss: 6.9021e-06 - acc: 1.0000
Epoch 54/100
 - 0s - loss: 6.6523e-06 - acc: 1.0000
Epoch 55/100
 - 0s - loss: 6.4066e-06 - acc: 1.0000
Epoch 56/100
 - 0s - loss: 6.1965e-06 - acc: 1.0000
Epoch 57/100
 - 0s - loss: 5.9773e-06 - acc: 1.0000
Epoch 58/100
 - 0s - loss: 5.7755e-06 - acc: 1.0000
Epoch 59/100
 - 0s - loss: 5.5982e-06 - acc: 1.0000
Epoch 60/100
 - 0s - loss: 5.4236e-06 - acc: 1.0000
Epoch 61/100
 - 0s - loss: 5.2341e-06 - acc: 1.0000
Epoch 62/100
 - 0s - loss: 5.0632e-06 - acc: 1.0000
Epoch 63/100
 - 0s - loss: 4.9109e-06 - acc: 1.0000
Epoch 64/100
 - 0s - loss: 4.7565e-06 - acc: 1.0000
Epoch 65/100
 - 0s - loss: 4.6077e-06 - acc: 1.0000
Epoch 66/100
 - 0s - loss: 4.4628e-06 - acc: 1.0000
Epoch 67/100
 - 0s - loss: 4.3331e-06 - acc: 1.0000
Epoch 68/100
 - 0s - loss: 4.2031e-06 - acc: 1.0000
Epoch 69/100
 - 0s - loss: 4.0799e-06 - acc: 1.0000
Epoch 70/100
 - 0s - loss: 3.9562e-06 - acc: 1.0000
Epoch 71/100
 - 0s - loss: 3.8523e-06 - acc: 1.0000
Epoch 72/100
 - 0s - loss: 3.7308e-06 - acc: 1.0000
Epoch 73/100
 - 0s - loss: 3.6316e-06 - acc: 1.0000
Epoch 74/100
 - 0s - loss: 3.5260e-06 - acc: 1.0000
Epoch 75/100
 - 0s - loss: 3.4329e-06 - acc: 1.0000
Epoch 76/100
 - 0s - loss: 3.3359e-06 - acc: 1.0000
Epoch 77/100
 - 0s - loss: 3.2506e-06 - acc: 1.0000
Epoch 78/100
 - 0s - loss: 3.1628e-06 - acc: 1.0000
Epoch 79/100
 - 0s - loss: 3.0837e-06 - acc: 1.0000
Epoch 80/100
 - 0s - loss: 3.0013e-06 - acc: 1.0000
Epoch 81/100
 - 0s - loss: 2.9232e-06 - acc: 1.0000
Epoch 82/100
 - 0s - loss: 2.8616e-06 - acc: 1.0000
Epoch 83/100
 - 0s - loss: 2.7773e-06 - acc: 1.0000
Epoch 84/100
 - 0s - loss: 2.7157e-06 - acc: 1.0000
Epoch 85/100
 - 0s - loss: 2.6435e-06 - acc: 1.0000
Epoch 86/100
 - 0s - loss: 2.5778e-06 - acc: 1.0000
Epoch 87/100
 - 0s - loss: 2.5190e-06 - acc: 1.0000
Epoch 88/100
 - 0s - loss: 2.4584e-06 - acc: 1.0000
Epoch 89/100
 - 0s - loss: 2.4015e-06 - acc: 1.0000
Epoch 90/100
 - 0s - loss: 2.3419e-06 - acc: 1.0000
Epoch 91/100
 - 0s - loss: 2.2910e-06 - acc: 1.0000
Epoch 92/100
 - 0s - loss: 2.2426e-06 - acc: 1.0000
Epoch 93/100
 - 0s - loss: 2.1895e-06 - acc: 1.0000
Epoch 94/100
 - 0s - loss: 2.1348e-06 - acc: 1.0000
Epoch 95/100
 - 0s - loss: 2.0944e-06 - acc: 1.0000
Epoch 96/100
 - 0s - loss: 2.0409e-06 - acc: 1.0000
Epoch 97/100
 - 0s - loss: 1.9949e-06 - acc: 1.0000
Epoch 98/100
 - 0s - loss: 1.9528e-06 - acc: 1.0000
Epoch 99/100
 - 0s - loss: 1.9107e-06 - acc: 1.0000
Epoch 100/100
 - 0s - loss: 1.8653e-06 - acc: 1.0000

In [42]:

model_loss, model_accuracy = model.evaluate(
    X_test_scaled, y_test_categorical, verbose=2)
print(
    f"Normal Neural Network - Loss: {model_loss}, Accuracy: {model_accuracy}")

Normal Neural Network - Loss: 5.199169338339626, Accuracy: 0.6336633675169236

In [43]:
# Save the model
model.save("dense_movie_classifier.h5")

In [44]:
# Load the model
from keras.models import load_model
dl_model = load_model("dense_movie_classifier.h5")

In [45]:
# # Dump the trained model with Pickle
# dl_pkl_filename = '../Resources/deep_learn_classifier_movie.pkl'
# # Open the file to save as pkl file
# dl_model_pkl = open(dl_pkl_filename, 'wb')
# pickle.dump(model, dl_model_pkl)
# # Close the pickle instances
# dl_model_pkl.close()

In [46]:
# # Load the Randon Forest model pickle
# dl_model_pkl = open('../Resources/deep_learn_classifier_movie.pkl', 'rb')
# dl_model = pickle.load(dl_model_pkl)

In [47]:
# y_train.iloc[3]
# X_train.iloc[3,:]
# X_test

In [48]:
encoded_predictions = model.predict_classes(X_test[:25])
prediction_labels = label_encoder.inverse_transform(encoded_predictions)

In [49]:
print(f"Predicted classes: {prediction_labels}")
print(f"Actual Labels: {list(y_test[:25])}")

Predicted classes: [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 0 1 1 1]
Actual Labels: [1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0]

In [22]:
# X_train.head()
# [X_train.iloc[0,:].values]